name: Fetch NSE Market Data

on:
  schedule:
    # Every minute, Mon–Fri, 3:45 AM – 10:00 AM UTC (= 9:15 AM – 3:30 PM IST)
    - cron: '* 3-9 * * 1-5'
    - cron: '0-30 10 * * 1-5'
  workflow_dispatch:   # Allow manual trigger from Actions tab

permissions:
  contents: write      # Needed to commit data.json back to repo

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install smartapi-python pyotp requests

      - name: Fetch market data
        env:
          AO_CLIENT_CODE: ${{ secrets.AO_CLIENT_CODE }}
          AO_API_KEY:      ${{ secrets.AO_API_KEY }}
          AO_TOTP_SECRET:  ${{ secrets.AO_TOTP_SECRET }}
          AO_MPIN:         ${{ secrets.AO_MPIN }}
        run: python fetch_market.py

      - name: Commit data.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          # Only commit if data.json actually changed
          git diff --staged --quiet || git commit -m "chore: update market data [skip ci]"
          git push
